.PHONY: clean All

All:
	@echo "----------Building project:[ bullscows - macOS ]----------"
	@cd "bullscows" && "$(MAKE)" -f  "bullscows.mk"
clean:
	@echo "----------Cleaning project:[ bullscows - macOS ]----------"
	@cd "bullscows" && "$(MAKE)" -f  "bullscows.mk" clean
